"""add cdr realtime table

Revision ID: 6e5b03508905
Revises: eb5c725922c5
Create Date: 2026-08-10 23:26:35.162390

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e5b03508905"
down_revision: Union[str, Sequence[str], None] = "eb5c725922c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cdr",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("calldate", sa.DateTime(), nullable=True),
        sa.Column("clid", sa.String(length=80), nullable=True),
        sa.Column("src", sa.String(length=80), nullable=True),
        sa.Column("dst", sa.String(length=80), nullable=True),
        sa.Column("dcontext", sa.String(length=80), nullable=True),
        sa.Column("channel", sa.String(length=80), nullable=True),
        sa.Column("dstchannel", sa.String(length=80), nullable=True),
        sa.Column("lastapp", sa.String(length=80), nullable=True),
        sa.Column("lastdata", sa.String(length=80), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("billsec", sa.Integer(), nullable=True),
        sa.Column("disposition", sa.String(length=45), nullable=True),
        sa.Column("amaflags", sa.Integer(), nullable=True),
        sa.Column("accountcode", sa.String(length=80), nullable=True),
        sa.Column("uniqueid", sa.String(length=150), nullable=True),
        sa.Column("userfield", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cdr")
    # ### end Alembic commands ###
