"""add pjsip realtime tables and number sip_password

Revision ID: de97b38e1af6
Revises: 1675cf372cfa
Create Date: 2026-08-10 22:56:18.878831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "de97b38e1af6"
down_revision: Union[str, Sequence[str], None] = "1675cf372cfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ps_aors",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("max_contacts", sa.Integer(), nullable=True),
        sa.Column("remove_existing", sa.String(length=3), nullable=True),
        sa.Column("support_path", sa.String(length=3), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ps_auths",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("auth_type", sa.String(length=40), nullable=True),
        sa.Column("username", sa.String(length=40), nullable=True),
        sa.Column("password", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ps_endpoints",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("transport", sa.String(length=40), nullable=True),
        sa.Column("aors", sa.String(length=200), nullable=True),
        sa.Column("auth", sa.String(length=40), nullable=True),
        sa.Column("context", sa.String(length=40), nullable=True),
        sa.Column("disallow", sa.String(length=200), nullable=True),
        sa.Column("allow", sa.String(length=200), nullable=True),
        sa.Column("direct_media", sa.String(length=3), nullable=True),
        sa.Column("dtmf_mode", sa.String(length=40), nullable=True),
        sa.Column("rtp_symmetric", sa.String(length=3), nullable=True),
        sa.Column("force_rport", sa.String(length=3), nullable=True),
        sa.Column("rewrite_contact", sa.String(length=3), nullable=True),
        sa.Column("callerid", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "numbers",
        sa.Column(
            "sip_password", sa.String(length=64), nullable=False, server_default=""
        ),
    )
    op.alter_column("numbers", "sip_password", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("numbers", "sip_password")
    op.drop_table("ps_endpoints")
    op.drop_table("ps_auths")
    op.drop_table("ps_aors")
    # ### end Alembic commands ###
